### Add Listing API Test
POST https://8080-idx-wanderer-1742544892672.cluster-fu5knmr55rd44vy7k7pxk74ams.cloudworkstations.dev/listings/add
Authorization: Bearer mysecretcodehere
{
  "listing": {
    "title": "Some Title",
    "description": "Some description...",
    "location": "Some City",
    "country": "Some Country",
    "price": 100,
    "image": ""
  }
}
